#Matrix  workflow
name: Date and Run_number_test    
on:
    workflow_dispatch:
          required: true 
    
#CI/CD job with matrix build          
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-m2
      - run: echo "::set-output name=today::$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      #- name: Echo current date
        #run: echo $NOW
      #-  name: Run Maven
         #run: mvn -f .github/workflows/pom.xml package
      
        #run: |
            #printf '{
              #"data_1": "Text data",
              #"data_2": true
              #}' >> testartifact.json
      #- uses: actions/upload-artifact@v4
        #with:
          #name: github-action-maven-tutorial-1.0-SNAPSHOT.jar
          #path: ./

              
              
      
       
 
          
                    
      

        

  
   
        
      
