#Matrix  workflow
name: Date and Run_number_test    
on:
    workflow_dispatch:
          required: true 
    
#CI/CD job with matrix build          
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: DATE PRINTING
              
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
            format: "YYYY_MM_DD HH_mm_ss_SSS"
# Use the output from the `t1` step
      - name: Output1
        run: |
            echo "The time was ${{ steps.t1.outputs.time }}"
            echo "The year was ${{ steps.t1.outputs.year }}"
            echo "The month was ${{ steps.t1.outputs.month }}"
            echo "The day was ${{ steps.t1.outputs.day }}"
        #run: echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV
        #run: "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Test with environment variables
        run: echo "Deploying at $BUILD_TIME"
        #- run: echo "date=($date +"%Y-%m-%d")" >> $GITHUB_ENV
          #uses: actions/checkout@v4
      #- name: Print the date
        #run: echo $GITHUB_ENV
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-m2
      
      #- name: Echo current date
        #run: echo $NOW
      #-  name: Run Maven
         #run: mvn -f .github/workflows/pom.xml package
      
        #run: |
            #printf '{
              #"data_1": "Text data",
              #"data_2": true
              #}' >> testartifact.json
      #- uses: actions/upload-artifact@v4
        #with:
          #name: github-action-maven-tutorial-1.0-SNAPSHOT.jar
          #path: ./

              
              
      
       
 
          
                    
      

        

  
   
        
      
