#Matrix  workflow
name: Cache dependencies
on:
    workflow_dispatch:
          required: true 
    
#CI/CD job with matrix build          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      #- name: Cache local Maven repository
        #uses: actions/cache@v3
        #with:
            #path: ~/.m2/repository
            #key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            #restore-keys: |
              #${{ runner.os }}-m2
      -  name: Run Maven
         run: mvn --batch-mode --update-snapshots verify
      -  run: mkdir staging && cp target/*.jar staging
        #run: |
            #printf '{
              #"data_1": "Text data",
              #"data_2": true
              #}' >> testartifact.json
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: staging

              
              
      
       
 
          
                    
      

        

  
   
        
      